// react-frontend/src/components/banner/Title.jsx
import React, { useEffect } from 'react';
import { useMatch } from 'react-router-dom';
import styles from './Title.module.scss';

function Title() {
    const match = useMatch('/sensor/:id');
    const title = match ? 'Sensor Detail' : 'All Sensors';

    return (
        <div className={styles.title}>
        <span>{title}</span>
        </div>
    );
}

export default Title;

// vue-frontend/src/components/banner/Title.vue
<script>
  import { defineComponent, computed } from 'vue';
  import { useRoute } from 'vue-router';
  
  export default defineComponent({
    setup() {
      const route = useRoute();
      const title = computed(() => {
        return route.path.includes('/sensor/') ? 'Sensor Detail' : 'All Sensors';
      });
  
      return {
        title,
        styles,
      };
    },
  });
</script>
  
<template>
    <div class="title">
        <span>{{ title }}</span>
    </div>
</template>
  
<style scoped>
  .title {
    font-weight: bold;
    color: white;
  }
</style>
