// vue-frontend/src/components/sensors/SensorTiles.vue
<script setup>
    import { ref, reactive, onMounted, onUnmounted } from 'vue';
    import axios from 'axios';
    import Tile from './Tile.vue';
    import PaginationButtons from '../shared/PaginationButtons.vue';
    
    const { expanded } = true;//useTileMode();
    const sensorData = ref([]);
    const currentPage = ref(1);
    const totalPages = ref(1);
    const loading = ref(true);

    const styleExpanded = { gridTemplateColumns: 'repeat(4, 1fr)' };
    const styleCollapsed = { gridTemplateColumns: 'repeat(10, 1fr)' };

    const fetchData = async () => {
        try {
            loading.value = true;
            const response = await axios.get(`http://localhost:3000/sensor?page=${currentPage.value}`);
            sensorData.value = response.data;
            totalPages.value = parseInt(response.headers['x-total-pages'], 10);
            loading.value = false;
        } catch (error) {
            console.error('Error fetching sensor data:', error);
            loading.value = false;
        }
    };

    const handlePrevPage = () => {
        currentPage.value -= 1;
    };

    const handleNextPage = () => {
        currentPage.value += 1;
    };

    const ws = new WebSocket('ws://localhost:8080');

    onMounted(async () => {
        await fetchData();
        ws.onmessage = (event) => {
            const newData = JSON.parse(event.data);
            updateSensorData(newData);
        };
    });

    onUnmounted(() => {
        ws.close();
    });

    const updateSensorData = (newData) => {
        const index = sensorData.value.findIndex(sensor => sensor.SensorId === newData.SensorId);
        if (index !== -1) {
            sensorData.value[index] = { ...sensorData.value[index], ...newData };
        }
    };
    
</script>

<template>
    <div class="sensorTiles" :style="[expanded ? styleExpanded : styleCollapsed]">
        <template v-if="loading">
            <div>Loading...</div>
        </template>
        <template v-else>
        <template v-for="(data, index) in sensorData" :key="index">
            <Tile :data="data" />
        </template>
        <div class="PaginationButtonsWrapper">
            <PaginationButtons
                :currentPage="currentPage"
                :totalPages="totalPages"
                @onPrevPage="handlePrevPage"
                @onNextPage="handleNextPage"
                :isNextDisabled="isNextDisabled"
            />
        </div>
        </template>
    </div>
</template>
  
<style scoped>
.SensorTiles {
    display: grid;
    gap: 20px;
    justify-items: center; 
    margin-top: 20px;
}
  
.PaginationButtonsWrapper {
    grid-column: 1 / -1; 
    justify-self: center;
    margin-top: 20px;

}
</style>

// react-frontend/src/components/sensors/SensorTiles.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import Tile from './Tile';
import PaginationButtons from '../shared/PaginationButtons';
import classes from './SensorTiles.module.css';
import { useTileMode } from '../../context/TileModeContext';

const SensorTiles = () => {
  const { expanded } = useTileMode();
  const [sensorData, setSensorData] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const ws = new WebSocket('ws://localhost:8080'); 

    ws.onmessage = (event) => {
      const newData = JSON.parse(event.data);
      updateSensorData(newData);
    };

    return () => {
      ws.close();
    };
  }, []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`http://localhost:3000/sensor?page=${currentPage}`);
        setSensorData(response.data);
        const totalPagesHeader = response.headers['x-total-pages'];
        setTotalPages(totalPagesHeader);
        setLoading(false); 
      } catch (error) {
        console.error('Error fetching sensor data:', error);
        setLoading(false); 
      }
    };
    fetchData();
  }, [currentPage]);

  const updateSensorData = (newData) => {
    setSensorData(prevData => {
      const index = prevData.findIndex(sensor => sensor.SensorId === newData.SensorId);
      if (index !== -1) {
        const updatedSensorData = [...prevData];
        updatedSensorData[index] = { ...updatedSensorData[index], ...newData };
        return updatedSensorData;
      }
      
      return prevData;
    });
  };

  const handlePrevPage = () => {
    setCurrentPage(currentPage - 1);
  };

  const handleNextPage = () => {
    setCurrentPage(currentPage + 1);
  };

  const isNextDisabled = currentPage === totalPages;
  const styleExpanded = {gridTemplateColumns: 'repeat(4, 1fr)'};
  const styleCollapsed = {gridTemplateColumns: 'repeat(10, 1fr)'};

  return (
    <div className={classes.SensorTiles} style={expanded ? styleExpanded : styleCollapsed}>
        {loading ? (
        <div>Loading...</div>
        ) : (
        <>
            {sensorData.map((data, index) => (
              <Tile key={index} data={data} />
            ))}
            <div className={classes.PaginationButtonsWrapper}>
              <PaginationButtons
                currentPage={currentPage}
                totalPages={totalPages}
                onPrevPage={handlePrevPage}
                onNextPage={handleNextPage}
                isNextDisabled={isNextDisabled}
              />
            </div>
        </>
        )}
    </div>
  );
};

export default SensorTiles;
