// react-frontend/src/SensorTiles.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import Tile from './Tile';

const PAGE_SIZE = 10;

const SensorTiles = () => {
  const [sensorData, setSensorData] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`http://localhost:3000/sensor?page=${currentPage}`);
        setSensorData(response.data);
        setLoading(false); 
      } catch (error) {
        console.error('Error fetching sensor data:', error);
        setLoading(false); 
      }
    };
    fetchData();
  }, [currentPage]);

  const handlePrevPage = () => {
    setCurrentPage(currentPage - 1);
  };

  const handleNextPage = () => {
    setCurrentPage(currentPage + 1);
  };

  return (
    <div>
        {loading ? (
        <div>Loading...</div>
        ) : (
        <>
            {sensorData.map((data, index) => (
            <Tile key={index} data={data} />
            ))}
            <div>
            <button onClick={handlePrevPage} disabled={currentPage === 1}>
                Prev
            </button>
            <button onClick={handleNextPage}>Next</button>
            </div>
        </>
        )}
    </div>
  );
};

export default SensorTiles;

// vue-frontend/src/components/sensors/SensorTiles.vue
<script>
  import { ref, reactive, watchEffect } from 'vue';
  import axios from 'axios';
  import Tile from './Tile.vue';
  import PaginationButtons from '../shared/PaginationButtons.vue';
  
  export default {
    components: {
      Tile,
      PaginationButtons,
    },
    setup() {
      const expanded = ref(false);
      const sensorData = ref([]);
      const currentPage = ref(1);
      const totalPages = ref(1);
      const loading = ref(true);
  
      const fetchData = async () => {
        try {
          loading.value = true;
          const response = await axios.get(`http://localhost:3000/sensor?page=${currentPage.value}`);
          sensorData.value = response.data;
          const totalPagesHeader = response.headers['x-total-pages'];
          totalPages.value = totalPagesHeader;
          loading.value = false;
        } catch (error) {
          console.error('Error fetching sensor data:', error);
          loading.value = false;
        }
      };
  
      watchEffect(() => {
        fetchData();
      });
  
      const handlePrevPage = () => {
        currentPage.value--;
      };
  
      const handleNextPage = () => {
        currentPage.value++;
      };
  
      const isNextDisabled = computed(() => currentPage.value === totalPages.value);
      const gridTemplateColumns = computed(() => expanded.value ? 'repeat(4, 1fr)' : 'repeat(10, 1fr)');
  
      return {
        expanded,
        sensorData,
        currentPage,
        totalPages,
        loading,
        handlePrevPage,
        handleNextPage,
        isNextDisabled,
        gridTemplateColumns,
      };
    },
  };
</script>

<template>
    <div class="SensorTiles" :style="{ gridTemplateColumns: gridTemplateColumns }">
      <div v-if="loading">Loading...</div>
      <div v-else>
        <Tile v-for="(data, index) in sensorData" :key="index" :data="data" />
        <div class="PaginationButtonsWrapper">
          <PaginationButtons
            :currentPage="currentPage"
            :totalPages="totalPages"
            @prevPage="handlePrevPage"
            @nextPage="handleNextPage"
            :isNextDisabled="isNextDisabled"
          />
        </div>
      </div>
    </div>
  </template>
  
  <style scoped>
  .SensorTiles {
    display: grid;
    gap: 20px;
    justify-items: center; 
    margin-top: 20px;
    }
    
    .PaginationButtonsWrapper {
        grid-column: 1 / -1; 
        justify-self: center;
        margin-top: 20px;

    }
  </style>
