// react-frontend/src/components/sensors/TwentyFourHoursHistoryChart.jsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTools } from '@fortawesome/free-solid-svg-icons';
import classes from './Sensor.module.scss';

const TwentyFourHoursHistoryChart = () => {
  return (
    <div className={classes.Sensor}>
      <div className={classes.icon}>
        <FontAwesomeIcon icon={faTools} size="6x" />
      </div>
      <div className={classes.message}>
        Chart Under Construction
      </div>
    </div>
  );
};

export default TwentyFourHoursHistoryChart;

// vue-frontend/src/components/sensors/TwentyFourHoursHistoryChart.vue
<script>
import { faTools } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

export default {
  components: {
    FontAwesomeIcon,
  },
  data() {
    return {
      faTools,
    };
  },
};
</script>

<template>
    <div class="Sensor">
      <div class="icon">
        <font-awesome-icon icon="faTools" size="6x" />
      </div>
      <div class="message">
        Chart Under Construction
      </div>
    </div>
</template>
  
  <style scoped>
  .Sensor {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .icon {
    margin-bottom: 20px;
  }
  
  .message {
    font-size: 24px;
    font-weight: bold;
  }
  </style>
