// vue-frontend/src/App.vue
<script setup>
  import Header from './components/header/Header.vue';
  import Banner from './components/banner/Banner.vue';
  import Main from './components/Main.vue';
</script>
  
<template>
  <div class="app">
    <Header />
    <Banner />
    <Main />
  </div>
  </template>
  
  
  <style scoped>
  .app {
    background-color: white;
  }
  </style>

// react-frontend/src/App.jsx
import React from 'react';
import classes from './App.module.scss';
import Header from './components/header/Header';
import Banner from './components/banner/Banner';
import Main from './components/Main';

const App = () => (
  <div className={classes.app}>
    <Header />
    <Banner />
    <Main/>
  </div>
);

export default App;
