// vue-frontend/src/components/banner/Banner.vue
<script>
    import { defineComponent } from 'vue';
    import Title from './Title.vue';
    import TileMode from './TileMode.vue';
    import Search from './Search.vue';
    import Logout from './Logout.vue';
</script>

<template>
  <div class=".banner">
    <Title />
    <div class="actions">
      <TileMode />
      <Search />
      <Logout />
    </div>
  </div>
</template>

<style scoped module>
.banner {
    background-color: #4974A3;
    padding: 10px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
  }
.actions {
display: flex;
}
</style>

// react-frontend/src/components/banner/Banner.jsx
import React from 'react';
import Title from './Title';
import TileMode from './TileMode';
import Search from './Search';
import Logout from './Logout';
import styles from './Banner.module.scss';

function Banner() {
    return (
        <div className={styles.banner}>
        <Title />
        <div className={styles.actions}>
            <TileMode />
            <Search />
            <Logout />
        </div>
        </div>
    );
}
  
export default Banner;
